### ISSUE TITLE
How to pull arguments?

### ISSUE THREAD

**Issue by ghost** [ReSpeak/SimpleBot#4]
how to add command like:

.test <argument1> <argument2> <argument3> <argument4>

and when i run it that have to do:

respond on teamspeak like: Successfuly started <argument1> for <argument2> to <argument3> end <argument4>
and run command via "shell" or "command" like: echo <argument1> <argument2> <argument3> <argument4>

how to do that?

**Comment by Flakebi** [comment]
I’m not sure what you mean.

If you cant to let the bot say “Successfully started“ on `.test`, you can add it like this:
```
.add Successfully started on .test
```

To run shell commands, you have to edit the configuration file like written in the readme.

**Comment by ghost** [comment]
No, i mean, how to add command, and run it like, .command I Love ReSpeak, and that command need to run shell command with that words "I Love ReSpeak", and if i run it with another words etc .command Wow its amazing, it needs to do shell command with "Wow its amazing" etc: echo Wow its amazing > done.txt

**Comment by Flakebi** [comment]
The following config snippet should do that (untested):
```toml
[[actions.on_message]]
regex = "^\\.command"
shell = "printf \"%s\" \"$4\" > done.txt"
```

**Comment by ghost** [comment]
im added that in settings.toml, and restarted bot, but nothing happends, how to add it?

**Comment by Flakebi** [comment]
Works fine for me, (it should have been $2 for the message):
```toml
[[actions.on_message]]
regex = "^\\.command"
shell = "printf \"%s\" \"$2\" > done.txt"
```

Edit: If I write `.command hello` in chat, the bot creates a file `done.txt` with the content `.command hello`.
Edit2: This works on Linux, on Windows you need other commands.
